import { createUseStyles } from 'react-jss';

export const Styles = createUseStyles({
  pageContainer: {
    background: '#f5f8fa',
    minHeight: '100vh',
    padding: '2rem',
  },
  headerContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '2rem',
    paddingTop: '2rem',
    gap: '1.5rem',
    flexWrap: 'wrap',
    background: '#f5f8fa',
  },
  title: {
    fontSize: '2.2rem',
    fontWeight: 700,
    color: '#1da1f2',
    letterSpacing: '1px',
    margin: 0,
  },
  card: {
    background: '#ffffff',
    borderRadius: 24,
    boxShadow: '0 8px 32px rgba(29,161,242,0.18)',
    padding: '2.5rem 2rem 2rem 2rem',
    width: '100%',
    maxWidth: 420,
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
    margin: '0 auto',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
  },
  label: {
    fontWeight: 500,
    color: '#14171a',
    marginBottom: '0.25rem',
    display: 'flex',
    flexDirection: 'column',
    fontSize: '1rem',
    letterSpacing: '0.01em',
  },
  input: {
    border: '1.5px solid #e6ecf0',
    borderRadius: 16,
    padding: '0.5rem 1rem',
    fontSize: '1.05rem',
    color: '#14171a',
    outline: 'none',
    transition: 'border 0.18s, box-shadow 0.18s',
    background: '#fff',
    fontWeight: 500,
    marginTop: '0.25rem',
    '&:focus': {
      border: '1.5px solid #1da1f2',
      boxShadow: '0 2px 8px rgba(29,161,242,0.10)',
    },
    '&::placeholder': {
      color: '#657786',
      opacity: 1,
    },
  },
  error: {
    color: '#d63031',
    fontSize: '0.95rem',
    marginTop: '0.25rem',
    fontWeight: 500,
    letterSpacing: '0.01em',
    lineHeight: 1.3,
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '1rem',
    marginTop: '1rem',
  },
});
